# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import visier_data_handling_python_sdk
from visier_data_handling_python_sdk.paths.v1_op_jobs_dispatching_jobs_job_id_processing_jobs import get
from visier_data_handling_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1OpJobsDispatchingJobsJobIdProcessingJobs(ApiTestMixin, unittest.TestCase):
    """
    V1OpJobsDispatchingJobsJobIdProcessingJobs unit test stubs
        Retrieve a dispatching job's processing jobs with their statuses
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
