# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_data_handling_python_sdk
from visier_data_handling_python_sdk.model.dayforce_v2_auth_params_dto import DayforceV2AuthParamsDTO
from visier_data_handling_python_sdk import configuration


class TestDayforceV2AuthParamsDTO(unittest.TestCase):
    """DayforceV2AuthParamsDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
