# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_data_handling_python_sdk
from visier_data_handling_python_sdk.model.tenant_data_upload_status_response_dto import TenantDataUploadStatusResponseDTO
from visier_data_handling_python_sdk import configuration


class TestTenantDataUploadStatusResponseDTO(unittest.TestCase):
    """TenantDataUploadStatusResponseDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
