# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_data_handling_python_sdk.paths.v1_op_data_connectors_assign_credentials.post import AssignConnectorCredentialRaw
from visier_data_handling_python_sdk.paths.v1_op_jobs_cancel.post import CancelJobsRaw
from visier_data_handling_python_sdk.paths.v1_op_data_connector_credentials.post import CreateConnectorCredentialRaw
from visier_data_handling_python_sdk.paths.v1_op_data_connector_credentials.get import DataConnectorCredentialsRaw
from visier_data_handling_python_sdk.paths.v1_op_data_connectors.get import DataConnectorsRaw
from visier_data_handling_python_sdk.paths.v1_op_data_connector_credentials_id.delete import DeleteConnectorCredentialRaw
from visier_data_handling_python_sdk.paths.v1_op_data_versions_disable.put import DisableDvRaw
from visier_data_handling_python_sdk.paths.v1_op_jobs_dispatching_jobs_job_id.get import DispatchingJobStatusRaw
from visier_data_handling_python_sdk.paths.v1_op_data_uploads_exclude.put import ExcludeDataUplaodsRaw
from visier_data_handling_python_sdk.paths.v1_op_jobs_dispatching_jobs_job_id_extraction_jobs.get import ExtractionJobAndStatusRaw
from visier_data_handling_python_sdk.paths.v1_op_data_uploads_include.put import IncludeDataUploadsRaw
from visier_data_handling_python_sdk.paths.v1_op_job_status_jobs_job_id.get import JobIdStatusRaw
from visier_data_handling_python_sdk.paths.v1_op_job_status_jobs.get import JobStatusRaw
from visier_data_handling_python_sdk.paths.v1_op_data_versions.get import LatestEnabledDvRaw
from visier_data_handling_python_sdk.paths.v1_op_jobs_dispatching_jobs_job_id_processing_jobs.get import ProcessingJobAndStatusRaw
from visier_data_handling_python_sdk.paths.v1_op_jobs_processing_jobs_receiving_job_id.get import ProcessingJobStatusRaw
from visier_data_handling_python_sdk.paths.v1_op_jobs_dispatching_jobs_job_id_receiving_jobs.get import ReceivingJobAndStatusRaw
from visier_data_handling_python_sdk.paths.v1_op_jobs_receiving_jobs_receiving_job_id.get import ReceivingJobStatusRaw
from visier_data_handling_python_sdk.paths.v1_op_data_uploads.get import RetrieveDataUploadsRaw
from visier_data_handling_python_sdk.paths.v1_op_data_start_extract_and_load.post import StartExtractionRaw
from visier_data_handling_python_sdk.paths.v1_op_data_startload.post import StartLoadRaw


class DataAndJobHandlingApiRaw(
    AssignConnectorCredentialRaw,
    CancelJobsRaw,
    CreateConnectorCredentialRaw,
    DataConnectorCredentialsRaw,
    DataConnectorsRaw,
    DeleteConnectorCredentialRaw,
    DisableDvRaw,
    DispatchingJobStatusRaw,
    ExcludeDataUplaodsRaw,
    ExtractionJobAndStatusRaw,
    IncludeDataUploadsRaw,
    JobIdStatusRaw,
    JobStatusRaw,
    LatestEnabledDvRaw,
    ProcessingJobAndStatusRaw,
    ProcessingJobStatusRaw,
    ReceivingJobAndStatusRaw,
    ReceivingJobStatusRaw,
    RetrieveDataUploadsRaw,
    StartExtractionRaw,
    StartLoadRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
