# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_data_handling_python_sdk.paths.v1_op_data_connectors_assign_credentials.post import AssignConnectorCredential
from visier_data_handling_python_sdk.paths.v1_op_jobs_cancel.post import CancelJobs
from visier_data_handling_python_sdk.paths.v1_op_data_connector_credentials.post import CreateConnectorCredential
from visier_data_handling_python_sdk.paths.v1_op_data_connector_credentials.get import DataConnectorCredentials
from visier_data_handling_python_sdk.paths.v1_op_data_connectors.get import DataConnectors
from visier_data_handling_python_sdk.paths.v1_op_data_connector_credentials_id.delete import DeleteConnectorCredential
from visier_data_handling_python_sdk.paths.v1_op_data_versions_disable.put import DisableDv
from visier_data_handling_python_sdk.paths.v1_op_jobs_dispatching_jobs_job_id.get import DispatchingJobStatus
from visier_data_handling_python_sdk.paths.v1_op_data_uploads_exclude.put import ExcludeDataUplaods
from visier_data_handling_python_sdk.paths.v1_op_jobs_dispatching_jobs_job_id_extraction_jobs.get import ExtractionJobAndStatus
from visier_data_handling_python_sdk.paths.v1_op_data_uploads_include.put import IncludeDataUploads
from visier_data_handling_python_sdk.paths.v1_op_job_status_jobs_job_id.get import JobIdStatus
from visier_data_handling_python_sdk.paths.v1_op_job_status_jobs.get import JobStatus
from visier_data_handling_python_sdk.paths.v1_op_data_versions.get import LatestEnabledDv
from visier_data_handling_python_sdk.paths.v1_op_jobs_dispatching_jobs_job_id_processing_jobs.get import ProcessingJobAndStatus
from visier_data_handling_python_sdk.paths.v1_op_jobs_processing_jobs_receiving_job_id.get import ProcessingJobStatus
from visier_data_handling_python_sdk.paths.v1_op_jobs_dispatching_jobs_job_id_receiving_jobs.get import ReceivingJobAndStatus
from visier_data_handling_python_sdk.paths.v1_op_jobs_receiving_jobs_receiving_job_id.get import ReceivingJobStatus
from visier_data_handling_python_sdk.paths.v1_op_data_uploads.get import RetrieveDataUploads
from visier_data_handling_python_sdk.paths.v1_op_data_start_extract_and_load.post import StartExtraction
from visier_data_handling_python_sdk.paths.v1_op_data_startload.post import StartLoad
from visier_data_handling_python_sdk.apis.tags.data_and_job_handling_api_raw import DataAndJobHandlingApiRaw


class DataAndJobHandlingApi(
    AssignConnectorCredential,
    CancelJobs,
    CreateConnectorCredential,
    DataConnectorCredentials,
    DataConnectors,
    DeleteConnectorCredential,
    DisableDv,
    DispatchingJobStatus,
    ExcludeDataUplaods,
    ExtractionJobAndStatus,
    IncludeDataUploads,
    JobIdStatus,
    JobStatus,
    LatestEnabledDv,
    ProcessingJobAndStatus,
    ProcessingJobStatus,
    ReceivingJobAndStatus,
    ReceivingJobStatus,
    RetrieveDataUploads,
    StartExtraction,
    StartLoad,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DataAndJobHandlingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DataAndJobHandlingApiRaw(api_client)
