# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_data_handling_python_sdk import schemas  # noqa: F401


class AssignConnectorWithCredentialsResponseDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def connector() -> typing.Type['ConnectorInfoResponseDTO']:
                return ConnectorInfoResponseDTO
        
            @staticmethod
            def credential() -> typing.Type['AssignedCredentialInfoResponseDTO']:
                return AssignedCredentialInfoResponseDTO
            __annotations__ = {
                "connector": connector,
                "credential": credential,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["connector"]) -> 'ConnectorInfoResponseDTO': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["credential"]) -> 'AssignedCredentialInfoResponseDTO': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["connector", "credential", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["connector"]) -> typing.Union['ConnectorInfoResponseDTO', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["credential"]) -> typing.Union['AssignedCredentialInfoResponseDTO', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["connector", "credential", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        connector: typing.Union['ConnectorInfoResponseDTO', schemas.Unset] = schemas.unset,
        credential: typing.Union['AssignedCredentialInfoResponseDTO', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AssignConnectorWithCredentialsResponseDTO':
        return super().__new__(
            cls,
            *args,
            connector=connector,
            credential=credential,
            _configuration=_configuration,
            **kwargs,
        )

from visier_data_handling_python_sdk.model.assigned_credential_info_response_dto import AssignedCredentialInfoResponseDTO
from visier_data_handling_python_sdk.model.connector_info_response_dto import ConnectorInfoResponseDTO
