# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_data_handling_python_sdk import schemas  # noqa: F401


class JiraConnectParamsDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            appKey = schemas.StrSchema
            clientKey = schemas.StrSchema
            sharedSecret = schemas.StrSchema
            __annotations__ = {
                "appKey": appKey,
                "clientKey": clientKey,
                "sharedSecret": sharedSecret,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["appKey"]) -> MetaOapg.properties.appKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientKey"]) -> MetaOapg.properties.clientKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sharedSecret"]) -> MetaOapg.properties.sharedSecret: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["appKey", "clientKey", "sharedSecret", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["appKey"]) -> typing.Union[MetaOapg.properties.appKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientKey"]) -> typing.Union[MetaOapg.properties.clientKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sharedSecret"]) -> typing.Union[MetaOapg.properties.sharedSecret, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["appKey", "clientKey", "sharedSecret", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        appKey: typing.Union[MetaOapg.properties.appKey, str, schemas.Unset] = schemas.unset,
        clientKey: typing.Union[MetaOapg.properties.clientKey, str, schemas.Unset] = schemas.unset,
        sharedSecret: typing.Union[MetaOapg.properties.sharedSecret, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'JiraConnectParamsDTO':
        return super().__new__(
            cls,
            *args,
            appKey=appKey,
            clientKey=clientKey,
            sharedSecret=sharedSecret,
            _configuration=_configuration,
            **kwargs,
        )
