# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_data_handling_python_sdk import schemas  # noqa: F401


class TenantDataUploadsUpdateResponseDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            totalFailures = schemas.IntSchema
            totalSuccess = schemas.IntSchema
            
            
            class uploads(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['TenantDataUploadUpdateStatusResponseDTO']:
                        return TenantDataUploadUpdateStatusResponseDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['TenantDataUploadUpdateStatusResponseDTO'], typing.List['TenantDataUploadUpdateStatusResponseDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'uploads':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'TenantDataUploadUpdateStatusResponseDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "totalFailures": totalFailures,
                "totalSuccess": totalSuccess,
                "uploads": uploads,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalFailures"]) -> MetaOapg.properties.totalFailures: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalSuccess"]) -> MetaOapg.properties.totalSuccess: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["uploads"]) -> MetaOapg.properties.uploads: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["totalFailures", "totalSuccess", "uploads", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalFailures"]) -> typing.Union[MetaOapg.properties.totalFailures, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalSuccess"]) -> typing.Union[MetaOapg.properties.totalSuccess, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["uploads"]) -> typing.Union[MetaOapg.properties.uploads, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["totalFailures", "totalSuccess", "uploads", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        totalFailures: typing.Union[MetaOapg.properties.totalFailures, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        totalSuccess: typing.Union[MetaOapg.properties.totalSuccess, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        uploads: typing.Union[MetaOapg.properties.uploads, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TenantDataUploadsUpdateResponseDTO':
        return super().__new__(
            cls,
            *args,
            totalFailures=totalFailures,
            totalSuccess=totalSuccess,
            uploads=uploads,
            _configuration=_configuration,
            **kwargs,
        )

from visier_data_handling_python_sdk.model.tenant_data_upload_update_status_response_dto import TenantDataUploadUpdateStatusResponseDTO
