# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_data_handling_python_sdk import schemas  # noqa: F401


class UploadToExclude(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            tenantCode = schemas.StrSchema
            excludeAll = schemas.BoolSchema
        
            @staticmethod
            def uploadTimes() -> typing.Type['UploadToExcludeUploadTimes']:
                return UploadToExcludeUploadTimes
            __annotations__ = {
                "tenantCode": tenantCode,
                "excludeAll": excludeAll,
                "uploadTimes": uploadTimes,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tenantCode"]) -> MetaOapg.properties.tenantCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["excludeAll"]) -> MetaOapg.properties.excludeAll: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["uploadTimes"]) -> 'UploadToExcludeUploadTimes': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["tenantCode", "excludeAll", "uploadTimes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tenantCode"]) -> typing.Union[MetaOapg.properties.tenantCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["excludeAll"]) -> typing.Union[MetaOapg.properties.excludeAll, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["uploadTimes"]) -> typing.Union['UploadToExcludeUploadTimes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["tenantCode", "excludeAll", "uploadTimes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        tenantCode: typing.Union[MetaOapg.properties.tenantCode, str, schemas.Unset] = schemas.unset,
        excludeAll: typing.Union[MetaOapg.properties.excludeAll, bool, schemas.Unset] = schemas.unset,
        uploadTimes: typing.Union['UploadToExcludeUploadTimes', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UploadToExclude':
        return super().__new__(
            cls,
            *args,
            tenantCode=tenantCode,
            excludeAll=excludeAll,
            uploadTimes=uploadTimes,
            _configuration=_configuration,
            **kwargs,
        )

from visier_data_handling_python_sdk.model.upload_to_exclude_upload_times import UploadToExcludeUploadTimes
