# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.assign_connector_credentials_by_tenant_response_dto import AssignConnectorCredentialsByTenantResponseDTO

class AssignConnectorCredentialsResponseDTO(BaseModel):
    # A list of objects representing the tenants and data connectors that were assigned connector credentials.
    tenants: typing.Optional[typing.List[AssignConnectorCredentialsByTenantResponseDTO]] = Field(None, alias='tenants')
    class Config:
        arbitrary_types_allowed = True
