# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.assigned_credential_info_response_dto import AssignedCredentialInfoResponseDTO
from visier_data_handling_python_sdk.pydantic.connector_info_response_dto import ConnectorInfoResponseDTO

class AssignConnectorWithCredentialsResponseDTO(BaseModel):
    # The data connector that was assigned a connector credential.
    connector: typing.Optional[ConnectorInfoResponseDTO] = Field(None, alias='connector')

    # A connector credential that was assigned to a data connector
    credential: typing.Optional[AssignedCredentialInfoResponseDTO] = Field(None, alias='credential')
    class Config:
        arbitrary_types_allowed = True
