# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class BasicS3AuthParamsDTO(BaseModel):
    bucket_name: typing.Optional[str] = Field(None, alias='bucketName')

    bucket_region: typing.Optional[str] = Field(None, alias='bucketRegion')

    access_key: typing.Optional[str] = Field(None, alias='accessKey')

    secret_key: typing.Optional[str] = Field(None, alias='secretKey')

    path: typing.Optional[str] = Field(None, alias='path')
    class Config:
        arbitrary_types_allowed = True
