# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.big_query_service_account_params_dto import BigQueryServiceAccountParamsDTO

class BigQueryAuthParamsDTO(BaseModel):
    project_id: typing.Optional[str] = Field(None, alias='projectId')

    dataset_location: typing.Optional[str] = Field(None, alias='datasetLocation')

    refresh_token: typing.Optional[str] = Field(None, alias='refreshToken')

    client_id: typing.Optional[str] = Field(None, alias='clientId')

    client_secret: typing.Optional[str] = Field(None, alias='clientSecret')

    default_dataset: typing.Optional[str] = Field(None, alias='defaultDataset')

    service_account_params: typing.Optional[BigQueryServiceAccountParamsDTO] = Field(None, alias='serviceAccountParams')
    class Config:
        arbitrary_types_allowed = True
