# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.tenant_and_credential import TenantAndCredential

class Connector(BaseModel):
    # The unique identifier associated with the data connector.
    connector_id: typing.Optional[str] = Field(None, alias='connectorId')

    # A list of analytic tenants and credentials to be assigned to the connector.
    tenants: typing.Optional[typing.List[TenantAndCredential]] = Field(None, alias='tenants')
    class Config:
        arbitrary_types_allowed = True
