# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.adp_auth_params_dto import AdpAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.bamboo_auth_params_dto import BambooAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.basic_s3_auth_params_dto import BasicS3AuthParamsDTO
from visier_data_handling_python_sdk.pydantic.big_query_auth_params_dto import BigQueryAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.copy_s3_auth_params_dto import CopyS3AuthParamsDTO
from visier_data_handling_python_sdk.pydantic.dayforce_v2_auth_params_dto import DayforceV2AuthParamsDTO
from visier_data_handling_python_sdk.pydantic.dimensions_auth_params_dto import DimensionsAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.fusion_auth_params_dto import FusionAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.gong_auth_params_dto import GongAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.google_sheets_auth_params_dto import GoogleSheetsAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.google_workspace_auth_params_dto import GoogleWorkspaceAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.greenhouse_auth_params_dto import GreenhouseAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.icims_auth_params_dto import IcimsAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.internal_s3_auth_params_dto import InternalS3AuthParamsDTO
from visier_data_handling_python_sdk.pydantic.jdbc_auth_params_dto import JdbcAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.jira_auth_params_dto import JiraAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.lever_auth_params_dto import LeverAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.medallia_auth_params_dto import MedalliaAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.microsoft365_auth_params_dto import Microsoft365AuthParamsDTO
from visier_data_handling_python_sdk.pydantic.my_sql_auth_params_dto import MySqlAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.namely_auth_params_dto import NamelyAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.oracle_db_auth_params_dto import OracleDbAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.qualtrics_auth_params_dto import QualtricsAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.redshift_auth_params_dto import RedshiftAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.salesforce_auth_params_dto import SalesforceAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.salesforce_v2_auth_params_dto import SalesforceV2AuthParamsDTO
from visier_data_handling_python_sdk.pydantic.service_now_auth_params_dto import ServiceNowAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.slack_auth_params_dto import SlackAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.snowflake_auth_params_dto import SnowflakeAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.sql_server_auth_params_dto import SqlServerAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.success_factors_auth_params_dto import SuccessFactorsAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.ultimate_auth_params_dto import UltimateAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.willow_auth_params_dto import WillowAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.workday_auth_params_dto import WorkdayAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.workday_raas_auth_params_dto import WorkdayRaasAuthParamsDTO
from visier_data_handling_python_sdk.pydantic.zoom_auth_params_dto import ZoomAuthParamsDTO

class DataProviderAuthParamsDTO(BaseModel):
    tenant_domain_name: typing.Optional[str] = Field(None, alias='tenantDomainName')

    # The data provider associated with the credential.  - Valid values: UKG, Dimensions, Workday, Redshift, BasicS3, CopyS3, SqlServer, Snowflake
    provider: typing.Optional[Literal["Bamboo", "GoogleSheets", "Greenhouse", "Jira", "Lever", "Namely", "Qualtrics", "Salesforce", "UKG", "Workday", "Icims", "ServiceNow", "Jdbc", "BasicS3", "InternalS3", "CopyS3", "Redshift", "Snowflake", "BigQuery", "SqlServer", "Dimensions", "IcimsPartnerProviderRedshift", "Willow", "SuccessFactors", "IcimsV2", "ADP", "WorkdayV2", "ServiceNowV2", "Medallia", "Fusion", "SalesforceV2", "Gong", "Zoom", "GoogleCalendar", "UKGV2", "DayforceV2", "GoogleActivityReport", "Slack", "MySql", "WorkdayRaas", "Microsoft365", "GoogleWorkspace", "OracleDb", "SmartRecruiters"]] = Field(None, alias='provider')

    bamboo_auth_params: typing.Optional[BambooAuthParamsDTO] = Field(None, alias='bambooAuthParams')

    greenhouse_auth_params: typing.Optional[GreenhouseAuthParamsDTO] = Field(None, alias='greenhouseAuthParams')

    google_sheets_auth_params: typing.Optional[GoogleSheetsAuthParamsDTO] = Field(None, alias='googleSheetsAuthParams')

    jira_auth_params: typing.Optional[JiraAuthParamsDTO] = Field(None, alias='jiraAuthParams')

    lever_auth_params: typing.Optional[LeverAuthParamsDTO] = Field(None, alias='leverAuthParams')

    namely_auth_params: typing.Optional[NamelyAuthParamsDTO] = Field(None, alias='namelyAuthParams')

    qualtrics_auth_params: typing.Optional[QualtricsAuthParamsDTO] = Field(None, alias='qualtricsAuthParams')

    salesforce_auth_params: typing.Optional[SalesforceAuthParamsDTO] = Field(None, alias='salesforceAuthParams')

    ultimate_auth_params: typing.Optional[UltimateAuthParamsDTO] = Field(None, alias='ultimateAuthParams')

    workday_auth_params: typing.Optional[WorkdayAuthParamsDTO] = Field(None, alias='workdayAuthParams')

    icims_auth_params: typing.Optional[IcimsAuthParamsDTO] = Field(None, alias='icimsAuthParams')

    service_now_auth_params: typing.Optional[ServiceNowAuthParamsDTO] = Field(None, alias='serviceNowAuthParams')

    jdbc_auth_params: typing.Optional[JdbcAuthParamsDTO] = Field(None, alias='jdbcAuthParams')

    s3_auth_params: typing.Optional[BasicS3AuthParamsDTO] = Field(None, alias='s3AuthParams')

    internal_s3_auth_params: typing.Optional[InternalS3AuthParamsDTO] = Field(None, alias='internalS3AuthParams')

    copy_s3_auth_params: typing.Optional[CopyS3AuthParamsDTO] = Field(None, alias='copyS3AuthParams')

    redshift_auth_params: typing.Optional[RedshiftAuthParamsDTO] = Field(None, alias='redshiftAuthParams')

    snowflake_auth_params: typing.Optional[SnowflakeAuthParamsDTO] = Field(None, alias='snowflakeAuthParams')

    big_query_auth_params: typing.Optional[BigQueryAuthParamsDTO] = Field(None, alias='bigQueryAuthParams')

    sql_server_auth_params: typing.Optional[SqlServerAuthParamsDTO] = Field(None, alias='sqlServerAuthParams')

    dimensions_auth_params: typing.Optional[DimensionsAuthParamsDTO] = Field(None, alias='dimensionsAuthParams')

    willow_auth_params: typing.Optional[WillowAuthParamsDTO] = Field(None, alias='willowAuthParams')

    empty_auth_params: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='emptyAuthParams')

    success_factors_auth_params: typing.Optional[SuccessFactorsAuthParamsDTO] = Field(None, alias='successFactorsAuthParams')

    fusion_auth_params: typing.Optional[FusionAuthParamsDTO] = Field(None, alias='fusionAuthParams')

    adp_auth_params: typing.Optional[AdpAuthParamsDTO] = Field(None, alias='adpAuthParams')

    medallia_auth_params: typing.Optional[MedalliaAuthParamsDTO] = Field(None, alias='medalliaAuthParams')

    salesforce_v2_auth_params: typing.Optional[SalesforceV2AuthParamsDTO] = Field(None, alias='salesforceV2AuthParams')

    gong_auth_params: typing.Optional[GongAuthParamsDTO] = Field(None, alias='gongAuthParams')

    zoom_auth_params: typing.Optional[ZoomAuthParamsDTO] = Field(None, alias='zoomAuthParams')

    dayforce_v2_auth_params: typing.Optional[DayforceV2AuthParamsDTO] = Field(None, alias='dayforceV2AuthParams')

    slack_auth_params: typing.Optional[SlackAuthParamsDTO] = Field(None, alias='slackAuthParams')

    my_sql_auth_params: typing.Optional[MySqlAuthParamsDTO] = Field(None, alias='mySqlAuthParams')

    workday_raas_auth_params: typing.Optional[WorkdayRaasAuthParamsDTO] = Field(None, alias='workdayRaasAuthParams')

    ms365_auth_params: typing.Optional[Microsoft365AuthParamsDTO] = Field(None, alias='ms365AuthParams')

    google_workspace_auth_params: typing.Optional[GoogleWorkspaceAuthParamsDTO] = Field(None, alias='googleWorkspaceAuthParams')

    oracle_db_auth_params: typing.Optional[OracleDbAuthParamsDTO] = Field(None, alias='oracleDbAuthParams')

    has_updates: typing.Optional[bool] = Field(None, alias='hasUpdates')

    auth_context: typing.Optional[Literal["DefaultDataExtraction", "WorkplaceDynamicsDataExtraction", "Notification"]] = Field(None, alias='authContext')
    class Config:
        arbitrary_types_allowed = True
