# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class DataProviderBasicMetadataDTO(BaseModel):
    can_children_inherit: typing.Optional[bool] = Field(None, alias='canChildrenInherit')
    class Config:
        arbitrary_types_allowed = True
