# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.result import Result

class DisableDVResponse(BaseModel):
    # The number of data versions that failed during the disabling process.
    total_failures: typing.Optional[int] = Field(None, alias='totalFailures')

    # The number of data versions that were disabled successfully.
    total_success: typing.Optional[int] = Field(None, alias='totalSuccess')

    # A list of objects representing the disabling process.
    results: typing.Optional[typing.List[Result]] = Field(None, alias='results')
    class Config:
        arbitrary_types_allowed = True
