# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class DispatchingJobStatusResponse(BaseModel):
    # The ID of the dispatching job that generated the extraction jobs.
    job_id: typing.Optional[str] = Field(None, alias='jobId')

    # The tenant that owns the dispatching job. This is usually the administrating tenant.
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # The current state of the job.
    status: typing.Optional[str] = Field(None, alias='status')

    # The number of extraction jobs that were generated by the dispatching job.
    total_jobs_dispatched: typing.Optional[int] = Field(None, alias='totalJobsDispatched')
    class Config:
        arbitrary_types_allowed = True
