# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ExtractionJob(BaseModel):
    # The ID of the extraction job.
    extraction_job_id: typing.Optional[str] = Field(None, alias='extractionJobId')

    # The tenant code of the analytic tenant for the extraction job.
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # The current state of the job.  - Valid values: Pending, Running, Succeeded, Failed, Error, Cancelling, Cancelled, RolledBack, Rescheduling, Rescheduled.
    status: typing.Optional[str] = Field(None, alias='status')

    # The current stage of the job. This is not returned if the stage is \"Completed\".  - Valid values: Initialize, Retrieve Main Subject, Retrieve Secondary Subjects, Retrieve Custom Subjects, Process Records, Publish Artifacts, Publish Records, Completed.
    current_stage: typing.Optional[str] = Field(None, alias='currentStage')
    class Config:
        arbitrary_types_allowed = True
