# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ExtractorCredentialAPIDTO(BaseModel):
    # The ID associated with the connector credential.
    credential_id: typing.Optional[str] = Field(None, alias='credentialId')

    # An identifiable connector credential name that is displayed within Visier.
    display_name: typing.Optional[str] = Field(None, alias='displayName')

    # The data provider associated with the credential.
    data_provider: typing.Optional[str] = Field(None, alias='dataProvider')

    # Whether this credential is inherited from another tenant.
    is_inherited: typing.Optional[bool] = Field(None, alias='isInherited')

    auth_context: typing.Optional[str] = Field(None, alias='authContext')
    class Config:
        arbitrary_types_allowed = True
