# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ImportDefinitionAPIDTO(BaseModel):
    # The ID associated with the data connector.
    connector_id: typing.Optional[str] = Field(None, alias='connectorId')

    # An identifiable data connector name that is displayed within Visier.
    display_name: typing.Optional[str] = Field(None, alias='displayName')

    # The ID associated with the connector credentials currently assigned to this data connector.
    credential_id: typing.Optional[str] = Field(None, alias='credentialId')
    class Config:
        arbitrary_types_allowed = True
