# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class MedalliaAuthParamsDTO(BaseModel):
    tenant_domain_name: typing.Optional[str] = Field(None, alias='tenantDomainName')

    instance_url: typing.Optional[str] = Field(None, alias='instanceUrl')

    client_id: typing.Optional[str] = Field(None, alias='clientId')

    client_secret: typing.Optional[str] = Field(None, alias='clientSecret')
    class Config:
        arbitrary_types_allowed = True
