# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.receiving_job import ReceivingJob

class ReceivingJobStatusResponse(BaseModel):
    # The unique identifier associated with the receiving job.
    job_id: typing.Optional[str] = Field(None, alias='jobId')

    # The status of the receiving job.
    status: typing.Optional[str] = Field(None, alias='status')

    # The job ID of the receiving job that spawned this job.
    parent_job_id: typing.Optional[str] = Field(None, alias='parentJobId')

    # The tenant code of the receiving job that spawned this job.
    parent_tenant_code: typing.Optional[str] = Field(None, alias='parentTenantCode')

    # A list of objects representing the receiving jobs to retrieve.
    receiving_jobs: typing.Optional[typing.List[ReceivingJob]] = Field(None, alias='receivingJobs')
    class Config:
        arbitrary_types_allowed = True
