# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.subject_missing_access_dto_attributes import SubjectMissingAccessDTOAttributes

class SubjectMissingAccessDTO(BaseModel):
    # The subjects that cannot be accessed.
    subject: typing.Optional[Literal["Employee", "Employee_Budgeted_Compensation", "Employment_Start", "Employment_Exit", "Absenteeism", "Supervisory", "Organization", "Compensation_Payout", "CustomSubject", "TestConnectionSubject", "Internal_Placement", "Pay_Change", "Hire", "Applicant", "Candidate", "Requisition"]] = Field(None, alias='subject')

    attributes: typing.Optional[SubjectMissingAccessDTOAttributes] = Field(None, alias='attributes')
    class Config:
        arbitrary_types_allowed = True
