# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.tenant_data_upload_update_status_response_dto import TenantDataUploadUpdateStatusResponseDTO

class TenantDataUploadsUpdateResponseDTO(BaseModel):
    # The number of data uploads that failed during the exclusion operation.
    total_failures: typing.Optional[int] = Field(None, alias='totalFailures')

    # The number of data uploads that were excluded successfully.
    total_success: typing.Optional[int] = Field(None, alias='totalSuccess')

    # A list of objects representing the results of the data upload exclusion.
    uploads: typing.Optional[typing.List[TenantDataUploadUpdateStatusResponseDTO]] = Field(None, alias='uploads')
    class Config:
        arbitrary_types_allowed = True
