# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class TenantDataUploadStatusResponseDTO(BaseModel):
    # The upload time of the data upload.
    upload_time: typing.Optional[str] = Field(None, alias='uploadTime')

    # If \"true\", the data upload is included.
    included: typing.Optional[bool] = Field(None, alias='included')
    class Config:
        arbitrary_types_allowed = True
