# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.upload_to_include_upload_times import UploadToIncludeUploadTimes

class UploadToInclude(BaseModel):
    # The tenant code of the analytic tenant you are including a data upload for.
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # If \"true\", all data uploads are included for the analytic tenant.
    include_all: typing.Optional[bool] = Field(None, alias='includeAll')

    upload_times: typing.Optional[UploadToIncludeUploadTimes] = Field(None, alias='uploadTimes')
    class Config:
        arbitrary_types_allowed = True
