# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_data_handling_python_sdk.pydantic.upload_to_include import UploadToInclude

class UploadToIncludeModel(BaseModel):
    # A list of objects representing the data uploads to include for a particular analytic tenant.
    uploads: typing.Optional[typing.List[UploadToInclude]] = Field(None, alias='uploads')
    class Config:
        arbitrary_types_allowed = True
