# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class WorkdayAuthParamsDTO(BaseModel):
    user_id: typing.Optional[str] = Field(None, alias='userId')

    domain_name: typing.Optional[str] = Field(None, alias='domainName')

    implementation_name: typing.Optional[str] = Field(None, alias='implementationName')

    password: typing.Optional[str] = Field(None, alias='password')

    integration_system_id: typing.Optional[str] = Field(None, alias='integrationSystemId')

    api_key: typing.Optional[str] = Field(None, alias='apiKey')
    class Config:
        arbitrary_types_allowed = True
