# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.assign_connector_with_credentials_response_dto import AssignConnectorWithCredentialsResponseDTO

class RequiredAssignConnectorCredentialsByTenantResponseDTO(TypedDict):
    pass

class OptionalAssignConnectorCredentialsByTenantResponseDTO(TypedDict, total=False):
    # The unique identifier associated with the tenant.
    tenantCode: str

    # A list of objects representing the assigned credentials and connectors.
    connectors: typing.List[AssignConnectorWithCredentialsResponseDTO]

    # The state of the credential assignment. Valid values are Succeed or Failed.
    status: str

    message: str

class AssignConnectorCredentialsByTenantResponseDTO(RequiredAssignConnectorCredentialsByTenantResponseDTO, OptionalAssignConnectorCredentialsByTenantResponseDTO):
    pass
