# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAssignedCredentialInfoResponseDTO(TypedDict):
    pass

class OptionalAssignedCredentialInfoResponseDTO(TypedDict, total=False):
    # The unique identifier associated with the user.
    credentialId: str

    # The user's username. This is typically the user's email, such as john@visier.com.
    displayName: str

    message: str

class AssignedCredentialInfoResponseDTO(RequiredAssignedCredentialInfoResponseDTO, OptionalAssignedCredentialInfoResponseDTO):
    pass
