# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.assigned_credential_info_response_dto import AssignedCredentialInfoResponseDTO
from visier_data_handling_python_sdk.type.connector_info_response_dto import ConnectorInfoResponseDTO

class RequiredAssignConnectorWithCredentialsResponseDTO(TypedDict):
    pass

class OptionalAssignConnectorWithCredentialsResponseDTO(TypedDict, total=False):
    # The data connector that was assigned a connector credential.
    connector: ConnectorInfoResponseDTO

    # A connector credential that was assigned to a data connector
    credential: AssignedCredentialInfoResponseDTO

class AssignConnectorWithCredentialsResponseDTO(RequiredAssignConnectorWithCredentialsResponseDTO, OptionalAssignConnectorWithCredentialsResponseDTO):
    pass
