# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.big_query_service_account_params_dto import BigQueryServiceAccountParamsDTO

class RequiredBigQueryAuthParamsDTO(TypedDict):
    pass

class OptionalBigQueryAuthParamsDTO(TypedDict, total=False):
    projectId: str

    datasetLocation: str

    refreshToken: str

    clientId: str

    clientSecret: str

    defaultDataset: str

    serviceAccountParams: BigQueryServiceAccountParamsDTO

class BigQueryAuthParamsDTO(RequiredBigQueryAuthParamsDTO, OptionalBigQueryAuthParamsDTO):
    pass
