# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.cancel_job_batch_from_job_id_dto_job_ids import CancelJobBatchFromJobIdDTOJobIds

class RequiredCancelJobBatchFromJobIdDTO(TypedDict):
    pass

class OptionalCancelJobBatchFromJobIdDTO(TypedDict, total=False):
    jobIds: CancelJobBatchFromJobIdDTOJobIds

class CancelJobBatchFromJobIdDTO(RequiredCancelJobBatchFromJobIdDTO, OptionalCancelJobBatchFromJobIdDTO):
    pass
