# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.tenant_and_credential import TenantAndCredential

class RequiredConnector(TypedDict):
    pass

class OptionalConnector(TypedDict, total=False):
    # The unique identifier associated with the data connector.
    connectorId: str

    # A list of analytic tenants and credentials to be assigned to the connector.
    tenants: typing.List[TenantAndCredential]

class Connector(RequiredConnector, OptionalConnector):
    pass
