# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredConnectorInfoResponseDTO(TypedDict):
    pass

class OptionalConnectorInfoResponseDTO(TypedDict, total=False):
    description: str

    # The unique identifier associated with the data connector.
    connectorId: str

    # An identifiable data connector name that is displayed within Visier.
    displayName: str

class ConnectorInfoResponseDTO(RequiredConnectorInfoResponseDTO, OptionalConnectorInfoResponseDTO):
    pass
