# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.data_provider_auth_params_dto import DataProviderAuthParamsDTO
from visier_data_handling_python_sdk.type.data_provider_basic_information_dto import DataProviderBasicInformationDTO
from visier_data_handling_python_sdk.type.data_provider_basic_metadata_dto import DataProviderBasicMetadataDTO

class RequiredDataProviderAuthInformationDTO(TypedDict):
    pass

class OptionalDataProviderAuthInformationDTO(TypedDict, total=False):
    # The authentication information for the credential.
    dataProviderAuthParams: DataProviderAuthParamsDTO

    # The display name and description for the credential.
    dataProviderBasicInformation: DataProviderBasicInformationDTO

    dataProviderMetadata: DataProviderBasicMetadataDTO

class DataProviderAuthInformationDTO(RequiredDataProviderAuthInformationDTO, OptionalDataProviderAuthInformationDTO):
    pass
