# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.adp_auth_params_dto import AdpAuthParamsDTO
from visier_data_handling_python_sdk.type.bamboo_auth_params_dto import BambooAuthParamsDTO
from visier_data_handling_python_sdk.type.basic_s3_auth_params_dto import BasicS3AuthParamsDTO
from visier_data_handling_python_sdk.type.big_query_auth_params_dto import BigQueryAuthParamsDTO
from visier_data_handling_python_sdk.type.copy_s3_auth_params_dto import CopyS3AuthParamsDTO
from visier_data_handling_python_sdk.type.dayforce_v2_auth_params_dto import DayforceV2AuthParamsDTO
from visier_data_handling_python_sdk.type.dimensions_auth_params_dto import DimensionsAuthParamsDTO
from visier_data_handling_python_sdk.type.fusion_auth_params_dto import FusionAuthParamsDTO
from visier_data_handling_python_sdk.type.gong_auth_params_dto import GongAuthParamsDTO
from visier_data_handling_python_sdk.type.google_sheets_auth_params_dto import GoogleSheetsAuthParamsDTO
from visier_data_handling_python_sdk.type.google_workspace_auth_params_dto import GoogleWorkspaceAuthParamsDTO
from visier_data_handling_python_sdk.type.greenhouse_auth_params_dto import GreenhouseAuthParamsDTO
from visier_data_handling_python_sdk.type.icims_auth_params_dto import IcimsAuthParamsDTO
from visier_data_handling_python_sdk.type.internal_s3_auth_params_dto import InternalS3AuthParamsDTO
from visier_data_handling_python_sdk.type.jdbc_auth_params_dto import JdbcAuthParamsDTO
from visier_data_handling_python_sdk.type.jira_auth_params_dto import JiraAuthParamsDTO
from visier_data_handling_python_sdk.type.lever_auth_params_dto import LeverAuthParamsDTO
from visier_data_handling_python_sdk.type.medallia_auth_params_dto import MedalliaAuthParamsDTO
from visier_data_handling_python_sdk.type.microsoft365_auth_params_dto import Microsoft365AuthParamsDTO
from visier_data_handling_python_sdk.type.my_sql_auth_params_dto import MySqlAuthParamsDTO
from visier_data_handling_python_sdk.type.namely_auth_params_dto import NamelyAuthParamsDTO
from visier_data_handling_python_sdk.type.oracle_db_auth_params_dto import OracleDbAuthParamsDTO
from visier_data_handling_python_sdk.type.qualtrics_auth_params_dto import QualtricsAuthParamsDTO
from visier_data_handling_python_sdk.type.redshift_auth_params_dto import RedshiftAuthParamsDTO
from visier_data_handling_python_sdk.type.salesforce_auth_params_dto import SalesforceAuthParamsDTO
from visier_data_handling_python_sdk.type.salesforce_v2_auth_params_dto import SalesforceV2AuthParamsDTO
from visier_data_handling_python_sdk.type.service_now_auth_params_dto import ServiceNowAuthParamsDTO
from visier_data_handling_python_sdk.type.slack_auth_params_dto import SlackAuthParamsDTO
from visier_data_handling_python_sdk.type.snowflake_auth_params_dto import SnowflakeAuthParamsDTO
from visier_data_handling_python_sdk.type.sql_server_auth_params_dto import SqlServerAuthParamsDTO
from visier_data_handling_python_sdk.type.success_factors_auth_params_dto import SuccessFactorsAuthParamsDTO
from visier_data_handling_python_sdk.type.ultimate_auth_params_dto import UltimateAuthParamsDTO
from visier_data_handling_python_sdk.type.willow_auth_params_dto import WillowAuthParamsDTO
from visier_data_handling_python_sdk.type.workday_auth_params_dto import WorkdayAuthParamsDTO
from visier_data_handling_python_sdk.type.workday_raas_auth_params_dto import WorkdayRaasAuthParamsDTO
from visier_data_handling_python_sdk.type.zoom_auth_params_dto import ZoomAuthParamsDTO

class RequiredDataProviderAuthParamsDTO(TypedDict):
    pass

class OptionalDataProviderAuthParamsDTO(TypedDict, total=False):
    tenantDomainName: str

    # The data provider associated with the credential.  - Valid values: UKG, Dimensions, Workday, Redshift, BasicS3, CopyS3, SqlServer, Snowflake
    provider: str

    bambooAuthParams: BambooAuthParamsDTO

    greenhouseAuthParams: GreenhouseAuthParamsDTO

    googleSheetsAuthParams: GoogleSheetsAuthParamsDTO

    jiraAuthParams: JiraAuthParamsDTO

    leverAuthParams: LeverAuthParamsDTO

    namelyAuthParams: NamelyAuthParamsDTO

    qualtricsAuthParams: QualtricsAuthParamsDTO

    salesforceAuthParams: SalesforceAuthParamsDTO

    ultimateAuthParams: UltimateAuthParamsDTO

    workdayAuthParams: WorkdayAuthParamsDTO

    icimsAuthParams: IcimsAuthParamsDTO

    serviceNowAuthParams: ServiceNowAuthParamsDTO

    jdbcAuthParams: JdbcAuthParamsDTO

    s3AuthParams: BasicS3AuthParamsDTO

    internalS3AuthParams: InternalS3AuthParamsDTO

    copyS3AuthParams: CopyS3AuthParamsDTO

    redshiftAuthParams: RedshiftAuthParamsDTO

    snowflakeAuthParams: SnowflakeAuthParamsDTO

    bigQueryAuthParams: BigQueryAuthParamsDTO

    sqlServerAuthParams: SqlServerAuthParamsDTO

    dimensionsAuthParams: DimensionsAuthParamsDTO

    willowAuthParams: WillowAuthParamsDTO

    emptyAuthParams: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    successFactorsAuthParams: SuccessFactorsAuthParamsDTO

    fusionAuthParams: FusionAuthParamsDTO

    adpAuthParams: AdpAuthParamsDTO

    medalliaAuthParams: MedalliaAuthParamsDTO

    salesforceV2AuthParams: SalesforceV2AuthParamsDTO

    gongAuthParams: GongAuthParamsDTO

    zoomAuthParams: ZoomAuthParamsDTO

    dayforceV2AuthParams: DayforceV2AuthParamsDTO

    slackAuthParams: SlackAuthParamsDTO

    mySqlAuthParams: MySqlAuthParamsDTO

    workdayRaasAuthParams: WorkdayRaasAuthParamsDTO

    ms365AuthParams: Microsoft365AuthParamsDTO

    googleWorkspaceAuthParams: GoogleWorkspaceAuthParamsDTO

    oracleDbAuthParams: OracleDbAuthParamsDTO

    hasUpdates: bool

    authContext: str

class DataProviderAuthParamsDTO(RequiredDataProviderAuthParamsDTO, OptionalDataProviderAuthParamsDTO):
    pass
