# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDataVersionAndDateDTO(TypedDict):
    pass

class OptionalDataVersionAndDateDTO(TypedDict, total=False):
    # The data version ID.
    dataVersion: str

    # The date that the data version was created.
    dataVersionDate: str

class DataVersionAndDateDTO(RequiredDataVersionAndDateDTO, OptionalDataVersionAndDateDTO):
    pass
