# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDimensionsAuthParamsDTO(TypedDict):
    pass

class OptionalDimensionsAuthParamsDTO(TypedDict, total=False):
    appKey: str

    clientId: str

    clientSecret: str

    vanityUrl: str

    username: str

    password: str

class DimensionsAuthParamsDTO(RequiredDimensionsAuthParamsDTO, OptionalDimensionsAuthParamsDTO):
    pass
