# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.data_version_object import DataVersionObject

class RequiredDisableDVModel(TypedDict):
    pass

class OptionalDisableDVModel(TypedDict, total=False):
    # A list of objects representing the data version to disable for a particular analytic tenant.  The limit of objects to include per request is 1000.
    dataVersionObjects: typing.List[DataVersionObject]

class DisableDVModel(RequiredDisableDVModel, OptionalDisableDVModel):
    pass
