# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.result import Result

class RequiredDisableDVResponse(TypedDict):
    pass

class OptionalDisableDVResponse(TypedDict, total=False):
    # The number of data versions that failed during the disabling process.
    totalFailures: int

    # The number of data versions that were disabled successfully.
    totalSuccess: int

    # A list of objects representing the disabling process.
    results: typing.List[Result]

class DisableDVResponse(RequiredDisableDVResponse, OptionalDisableDVResponse):
    pass
