# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.disable_dv_model import DisableDVModel

class RequiredDisableDVRequest(TypedDict):
    pass

class OptionalDisableDVRequest(TypedDict, total=False):
    # A form body key that contains a collection of key-value pairs.
    model: DisableDVModel

class DisableDVRequest(RequiredDisableDVRequest, OptionalDisableDVRequest):
    pass
