# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDispatchingJobStatusResponse(TypedDict):
    pass

class OptionalDispatchingJobStatusResponse(TypedDict, total=False):
    # The ID of the dispatching job that generated the extraction jobs.
    jobId: str

    # The tenant that owns the dispatching job. This is usually the administrating tenant.
    tenantCode: str

    # The current state of the job.
    status: str

    # The number of extraction jobs that were generated by the dispatching job.
    totalJobsDispatched: int

class DispatchingJobStatusResponse(RequiredDispatchingJobStatusResponse, OptionalDispatchingJobStatusResponse):
    pass
