# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.upload_to_exclude_model import UploadToExcludeModel

class RequiredExcludeDataUploadsRequest(TypedDict):
    pass

class OptionalExcludeDataUploadsRequest(TypedDict, total=False):
    # A form body key that contains a collection of key-value pairs.
    model: UploadToExcludeModel

class ExcludeDataUploadsRequest(RequiredExcludeDataUploadsRequest, OptionalExcludeDataUploadsRequest):
    pass
