# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredExtractionJob(TypedDict):
    pass

class OptionalExtractionJob(TypedDict, total=False):
    # The ID of the extraction job.
    extractionJobId: str

    # The tenant code of the analytic tenant for the extraction job.
    tenantCode: str

    # The current state of the job.  - Valid values: Pending, Running, Succeeded, Failed, Error, Cancelling, Cancelled, RolledBack, Rescheduling, Rescheduled.
    status: str

    # The current stage of the job. This is not returned if the stage is \"Completed\".  - Valid values: Initialize, Retrieve Main Subject, Retrieve Secondary Subjects, Retrieve Custom Subjects, Process Records, Publish Artifacts, Publish Records, Completed.
    currentStage: str

class ExtractionJob(RequiredExtractionJob, OptionalExtractionJob):
    pass
