# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredExtractorCredentialAPIDTO(TypedDict):
    pass

class OptionalExtractorCredentialAPIDTO(TypedDict, total=False):
    # The ID associated with the connector credential.
    credentialId: str

    # An identifiable connector credential name that is displayed within Visier.
    displayName: str

    # The data provider associated with the credential.
    dataProvider: str

    # Whether this credential is inherited from another tenant.
    isInherited: bool

    authContext: str

class ExtractorCredentialAPIDTO(RequiredExtractorCredentialAPIDTO, OptionalExtractorCredentialAPIDTO):
    pass
