# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredImportDefinitionAPIDTO(TypedDict):
    pass

class OptionalImportDefinitionAPIDTO(TypedDict, total=False):
    # The ID associated with the data connector.
    connectorId: str

    # An identifiable data connector name that is displayed within Visier.
    displayName: str

    # The ID associated with the connector credentials currently assigned to this data connector.
    credentialId: str

class ImportDefinitionAPIDTO(RequiredImportDefinitionAPIDTO, OptionalImportDefinitionAPIDTO):
    pass
