# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.data_version_and_date_dto import DataVersionAndDateDTO

class RequiredMultipleTenantDataVersionsDetailsDTO(TypedDict):
    pass

class OptionalMultipleTenantDataVersionsDetailsDTO(TypedDict, total=False):
    # The owner of the data versions.
    tenantCode: str

    # The latest enabled data versions for the given analytic tenant. If the analytic tenant  has no enabled data versions, an empty string \"\" is returned.
    dataVersions: typing.List[DataVersionAndDateDTO]

class MultipleTenantDataVersionsDetailsDTO(RequiredMultipleTenantDataVersionsDetailsDTO, OptionalMultipleTenantDataVersionsDetailsDTO):
    pass
