# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.receiving_job import ReceivingJob

class RequiredReceivingJobStatusResponse(TypedDict):
    pass

class OptionalReceivingJobStatusResponse(TypedDict, total=False):
    # The unique identifier associated with the receiving job.
    jobId: str

    # The status of the receiving job.
    status: str

    # The job ID of the receiving job that spawned this job.
    parentJobId: str

    # The tenant code of the receiving job that spawned this job.
    parentTenantCode: str

    # A list of objects representing the receiving jobs to retrieve.
    receivingJobs: typing.List[ReceivingJob]

class ReceivingJobStatusResponse(RequiredReceivingJobStatusResponse, OptionalReceivingJobStatusResponse):
    pass
