# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.start_extraction_model_tenants import StartExtractionModelTenants

class RequiredStartExtractionModel(TypedDict):
    pass

class OptionalStartExtractionModel(TypedDict, total=False):
    tenants: StartExtractionModelTenants

    # If \"true\", one extraction job is dispatched for each accessible analytic tenant.
    allTenants: bool

    # The time from which to extract data.
    overrideLastExtractionTimestamp: str

    # If \"true\", the generated data load artifacts are published to Production immediately.
    publishDataLoadArtifacts: bool

    # If \"true\", a processing job is spawned after a dispatched extraction job runs successfully.
    runProcessingJob: bool

    # The unique identifier of the data category on which to trigger the extraction job.
    dataCategoryId: str

    # If \"true\", the job does not generate data load artifacts. If unspecified, the default is \"false\".
    disableArtifactGeneration: bool

class StartExtractionModel(RequiredStartExtractionModel, OptionalStartExtractionModel):
    pass
