# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTenantDataUploadUpdateStatusResponseDTO(TypedDict):
    pass

class OptionalTenantDataUploadUpdateStatusResponseDTO(TypedDict, total=False):
    # The analytic tenant that the exclusion operation was conducted for.
    tenantCode: str

    # The upload time of the data upload
    uploadTime: str

    # The outcome of the exclusion operation.
    status: str

    # If applicable, the message explains why errors were encountered during the exclusion operation.
    message: str

class TenantDataUploadUpdateStatusResponseDTO(RequiredTenantDataUploadUpdateStatusResponseDTO, OptionalTenantDataUploadUpdateStatusResponseDTO):
    pass
