# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.tenant_data_upload_status_response_dto import TenantDataUploadStatusResponseDTO

class RequiredTenantDataUploadsResponseDTO(TypedDict):
    pass

class OptionalTenantDataUploadsResponseDTO(TypedDict, total=False):
    # The tenant code of the analytic tenant owning the data uploads.
    tenantCode: str

    # The data uploads completed for the specified analytic tenant. The list is empty if no previous data uploads are found for the analytic tenant.
    uploads: typing.List[TenantDataUploadStatusResponseDTO]

class TenantDataUploadsResponseDTO(RequiredTenantDataUploadsResponseDTO, OptionalTenantDataUploadsResponseDTO):
    pass
