# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.tenant_data_upload_update_status_response_dto import TenantDataUploadUpdateStatusResponseDTO

class RequiredTenantDataUploadsUpdateResponseDTO(TypedDict):
    pass

class OptionalTenantDataUploadsUpdateResponseDTO(TypedDict, total=False):
    # The number of data uploads that failed during the exclusion operation.
    totalFailures: int

    # The number of data uploads that were excluded successfully.
    totalSuccess: int

    # A list of objects representing the results of the data upload exclusion.
    uploads: typing.List[TenantDataUploadUpdateStatusResponseDTO]

class TenantDataUploadsUpdateResponseDTO(RequiredTenantDataUploadsUpdateResponseDTO, OptionalTenantDataUploadsUpdateResponseDTO):
    pass
