# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.upload_to_include_upload_times import UploadToIncludeUploadTimes

class RequiredUploadToInclude(TypedDict):
    pass

class OptionalUploadToInclude(TypedDict, total=False):
    # The tenant code of the analytic tenant you are including a data upload for.
    tenantCode: str

    # If \"true\", all data uploads are included for the analytic tenant.
    includeAll: bool

    uploadTimes: UploadToIncludeUploadTimes

class UploadToInclude(RequiredUploadToInclude, OptionalUploadToInclude):
    pass
