# coding: utf-8

"""
    Visier Data and Job Handling APIs

    Visier APIs for data and job handling

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_handling_python_sdk.type.upload_to_include import UploadToInclude

class RequiredUploadToIncludeModel(TypedDict):
    pass

class OptionalUploadToIncludeModel(TypedDict, total=False):
    # A list of objects representing the data uploads to include for a particular analytic tenant.
    uploads: typing.List[UploadToInclude]

class UploadToIncludeModel(RequiredUploadToIncludeModel, OptionalUploadToIncludeModel):
    pass
